#!/bin/sh
# shellcheck disable=SC1091,SC2034,SC2154

# Copyright (C) Igor Sysoev
# Copyright (C) Nginx, Inc.
# Copyright (C) Google Inc.
# Copyright (C) 2026 Juri Torhoff

# Make sure the module knows it is a submodule.
ngx_addon_name=ngx_pack
. "$ngx_addon_dir"/module/filter/zstd/config

# Make sure the module knows it is a submodule.
ngx_addon_name=ngx_pack
. "$ngx_addon_dir"/module/filter/brotli/config

# Make sure the module knows it is a submodule.
ngx_addon_name=ngx_pack
. "$ngx_addon_dir"/module/static/config

# The final name for reporting.
ngx_addon_name=ngx_pack
